//////////////////////////////////////////////////////////////////////////////////
// Company: AGH
// Engineer: Marcin Maj
// 
// Create Date: 07.07.2024 19:09:20
// Design Name: 
// Module Name: test_vectors.h
// Description: File contains test vectors stored in logic arrays. File is auto-generated by create_tv_file.py
// 
//////////////////////////////////////////////////////////////////////////////////

`ifndef TEST_VECTORS
`define TEST_VECTORS

localparam AMP_SWEEP_LEN = 7;
localparam WIDTH_SWEEP_LEN = 41;

typedef logic [IN_WIDTH-1:0] wave_t [0:PULSE_SAMPLES-1];
typedef logic                threshold_t [0:PULSE_SAMPLES-1];

wave_t      amplitude_sweep_waves      [0:AMP_SWEEP_LEN-1];
threshold_t amplitude_sweep_thresholds [0:AMP_SWEEP_LEN-1];
wave_t      width_sweep_waves          [0:WIDTH_SWEEP_LEN-1];
threshold_t width_sweep_thresholds     [0:WIDTH_SWEEP_LEN-1];

//////////////////////////////////////////////////
// AMPLITUDE SWEEP VECTORS
//////////////////////////////////////////////////
logic [IN_WIDTH-1:0] amplitude_11_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_1_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_21_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_31_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_41_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_51_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_61_wave_arr [0:PULSE_SAMPLES-1];
logic amplitude_11_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_1_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_21_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_31_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_41_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_51_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_61_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
//////////////////////////////////////////////////
// WIDTH SWEEP VECTORS
//////////////////////////////////////////////////
logic [IN_WIDTH-1:0] width_1000_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_1100_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_1200_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_1300_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_1400_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_1500_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_1600_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_1700_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_1800_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_1900_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_2000_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_2100_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_2200_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_2300_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_2400_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_2500_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_2600_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_2700_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_2800_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_2900_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_3000_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_3100_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_3200_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_3300_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_3400_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_3500_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_3600_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_3700_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_3800_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_3900_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_4000_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_4100_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_4200_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_4300_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_4400_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_4500_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_4600_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_4700_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_4800_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_4900_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_5000_wave_arr [0:PULSE_SAMPLES-1];
logic width_1000_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_1100_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_1200_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_1300_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_1400_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_1500_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_1600_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_1700_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_1800_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_1900_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_2000_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_2100_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_2200_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_2300_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_2400_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_2500_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_2600_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_2700_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_2800_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_2900_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_3000_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_3100_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_3200_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_3300_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_3400_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_3500_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_3600_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_3700_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_3800_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_3900_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_4000_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_4100_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_4200_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_4300_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_4400_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_4500_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_4600_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_4700_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_4800_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_4900_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_5000_threshold_sample_th_arr [0:PULSE_SAMPLES-1];

typedef enum {
  amplitude_11_,
  amplitude_1_,
  amplitude_21_,
  amplitude_31_,
  amplitude_41_,
  amplitude_51_,
  amplitude_61_
} amp_testname_t;


typedef enum {
  width_1000_,
  width_1100_,
  width_1200_,
  width_1300_,
  width_1400_,
  width_1500_,
  width_1600_,
  width_1700_,
  width_1800_,
  width_1900_,
  width_2000_,
  width_2100_,
  width_2200_,
  width_2300_,
  width_2400_,
  width_2500_,
  width_2600_,
  width_2700_,
  width_2800_,
  width_2900_,
  width_3000_,
  width_3100_,
  width_3200_,
  width_3300_,
  width_3400_,
  width_3500_,
  width_3600_,
  width_3700_,
  width_3800_,
  width_3900_,
  width_4000_,
  width_4100_,
  width_4200_,
  width_4300_,
  width_4400_,
  width_4500_,
  width_4600_,
  width_4700_,
  width_4800_,
  width_4900_,
  width_5000_
} width_testname_t;

width_testname_t width_testname = width_1000_;
amp_testname_t amp_testname = amplitude_11_;

initial begin
//////////////////////////////////////////////////
// LOADING AMPLITUDE SWEEP VALUES TO VECTORS
//////////////////////////////////////////////////
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_11_.txt", amplitude_11_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_1_.txt", amplitude_1_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_21_.txt", amplitude_21_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_31_.txt", amplitude_31_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_41_.txt", amplitude_41_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_51_.txt", amplitude_51_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_61_.txt", amplitude_61_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_11_threshold_sample_.txt", amplitude_11_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_1_threshold_sample_.txt", amplitude_1_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_21_threshold_sample_.txt", amplitude_21_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_31_threshold_sample_.txt", amplitude_31_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_41_threshold_sample_.txt", amplitude_41_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_51_threshold_sample_.txt", amplitude_51_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_61_threshold_sample_.txt", amplitude_61_threshold_sample_th_arr);
//////////////////////////////////////////////////
// LOADING WIDTH SWEEP VALUES TO VECTORS
//////////////////////////////////////////////////
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1000_.txt", width_1000_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1100_.txt", width_1100_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1200_.txt", width_1200_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1300_.txt", width_1300_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1400_.txt", width_1400_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1500_.txt", width_1500_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1600_.txt", width_1600_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1700_.txt", width_1700_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1800_.txt", width_1800_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1900_.txt", width_1900_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2000_.txt", width_2000_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2100_.txt", width_2100_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2200_.txt", width_2200_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2300_.txt", width_2300_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2400_.txt", width_2400_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2500_.txt", width_2500_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2600_.txt", width_2600_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2700_.txt", width_2700_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2800_.txt", width_2800_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2900_.txt", width_2900_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3000_.txt", width_3000_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3100_.txt", width_3100_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3200_.txt", width_3200_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3300_.txt", width_3300_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3400_.txt", width_3400_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3500_.txt", width_3500_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3600_.txt", width_3600_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3700_.txt", width_3700_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3800_.txt", width_3800_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3900_.txt", width_3900_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4000_.txt", width_4000_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4100_.txt", width_4100_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4200_.txt", width_4200_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4300_.txt", width_4300_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4400_.txt", width_4400_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4500_.txt", width_4500_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4600_.txt", width_4600_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4700_.txt", width_4700_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4800_.txt", width_4800_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4900_.txt", width_4900_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_5000_.txt", width_5000_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1000_threshold_sample_.txt", width_1000_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1100_threshold_sample_.txt", width_1100_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1200_threshold_sample_.txt", width_1200_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1300_threshold_sample_.txt", width_1300_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1400_threshold_sample_.txt", width_1400_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1500_threshold_sample_.txt", width_1500_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1600_threshold_sample_.txt", width_1600_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1700_threshold_sample_.txt", width_1700_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1800_threshold_sample_.txt", width_1800_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1900_threshold_sample_.txt", width_1900_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2000_threshold_sample_.txt", width_2000_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2100_threshold_sample_.txt", width_2100_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2200_threshold_sample_.txt", width_2200_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2300_threshold_sample_.txt", width_2300_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2400_threshold_sample_.txt", width_2400_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2500_threshold_sample_.txt", width_2500_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2600_threshold_sample_.txt", width_2600_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2700_threshold_sample_.txt", width_2700_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2800_threshold_sample_.txt", width_2800_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2900_threshold_sample_.txt", width_2900_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3000_threshold_sample_.txt", width_3000_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3100_threshold_sample_.txt", width_3100_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3200_threshold_sample_.txt", width_3200_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3300_threshold_sample_.txt", width_3300_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3400_threshold_sample_.txt", width_3400_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3500_threshold_sample_.txt", width_3500_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3600_threshold_sample_.txt", width_3600_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3700_threshold_sample_.txt", width_3700_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3800_threshold_sample_.txt", width_3800_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3900_threshold_sample_.txt", width_3900_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4000_threshold_sample_.txt", width_4000_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4100_threshold_sample_.txt", width_4100_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4200_threshold_sample_.txt", width_4200_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4300_threshold_sample_.txt", width_4300_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4400_threshold_sample_.txt", width_4400_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4500_threshold_sample_.txt", width_4500_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4600_threshold_sample_.txt", width_4600_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4700_threshold_sample_.txt", width_4700_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4800_threshold_sample_.txt", width_4800_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4900_threshold_sample_.txt", width_4900_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_5000_threshold_sample_.txt", width_5000_threshold_sample_th_arr);
end

initial begin
amplitude_sweep_waves[0] = amplitude_11_wave_arr;
amplitude_sweep_waves[1] = amplitude_1_wave_arr;
amplitude_sweep_waves[2] = amplitude_21_wave_arr;
amplitude_sweep_waves[3] = amplitude_31_wave_arr;
amplitude_sweep_waves[4] = amplitude_41_wave_arr;
amplitude_sweep_waves[5] = amplitude_51_wave_arr;
amplitude_sweep_waves[6] = amplitude_61_wave_arr;
amplitude_sweep_thresholds[0] = amplitude_11_threshold_sample_th_arr;
amplitude_sweep_thresholds[1] = amplitude_1_threshold_sample_th_arr;
amplitude_sweep_thresholds[2] = amplitude_21_threshold_sample_th_arr;
amplitude_sweep_thresholds[3] = amplitude_31_threshold_sample_th_arr;
amplitude_sweep_thresholds[4] = amplitude_41_threshold_sample_th_arr;
amplitude_sweep_thresholds[5] = amplitude_51_threshold_sample_th_arr;
amplitude_sweep_thresholds[6] = amplitude_61_threshold_sample_th_arr;
width_sweep_waves[0] = width_1000_wave_arr;
width_sweep_waves[1] = width_1100_wave_arr;
width_sweep_waves[2] = width_1200_wave_arr;
width_sweep_waves[3] = width_1300_wave_arr;
width_sweep_waves[4] = width_1400_wave_arr;
width_sweep_waves[5] = width_1500_wave_arr;
width_sweep_waves[6] = width_1600_wave_arr;
width_sweep_waves[7] = width_1700_wave_arr;
width_sweep_waves[8] = width_1800_wave_arr;
width_sweep_waves[9] = width_1900_wave_arr;
width_sweep_waves[10] = width_2000_wave_arr;
width_sweep_waves[11] = width_2100_wave_arr;
width_sweep_waves[12] = width_2200_wave_arr;
width_sweep_waves[13] = width_2300_wave_arr;
width_sweep_waves[14] = width_2400_wave_arr;
width_sweep_waves[15] = width_2500_wave_arr;
width_sweep_waves[16] = width_2600_wave_arr;
width_sweep_waves[17] = width_2700_wave_arr;
width_sweep_waves[18] = width_2800_wave_arr;
width_sweep_waves[19] = width_2900_wave_arr;
width_sweep_waves[20] = width_3000_wave_arr;
width_sweep_waves[21] = width_3100_wave_arr;
width_sweep_waves[22] = width_3200_wave_arr;
width_sweep_waves[23] = width_3300_wave_arr;
width_sweep_waves[24] = width_3400_wave_arr;
width_sweep_waves[25] = width_3500_wave_arr;
width_sweep_waves[26] = width_3600_wave_arr;
width_sweep_waves[27] = width_3700_wave_arr;
width_sweep_waves[28] = width_3800_wave_arr;
width_sweep_waves[29] = width_3900_wave_arr;
width_sweep_waves[30] = width_4000_wave_arr;
width_sweep_waves[31] = width_4100_wave_arr;
width_sweep_waves[32] = width_4200_wave_arr;
width_sweep_waves[33] = width_4300_wave_arr;
width_sweep_waves[34] = width_4400_wave_arr;
width_sweep_waves[35] = width_4500_wave_arr;
width_sweep_waves[36] = width_4600_wave_arr;
width_sweep_waves[37] = width_4700_wave_arr;
width_sweep_waves[38] = width_4800_wave_arr;
width_sweep_waves[39] = width_4900_wave_arr;
width_sweep_waves[40] = width_5000_wave_arr;
width_sweep_thresholds[0] = width_1000_threshold_sample_th_arr;
width_sweep_thresholds[1] = width_1100_threshold_sample_th_arr;
width_sweep_thresholds[2] = width_1200_threshold_sample_th_arr;
width_sweep_thresholds[3] = width_1300_threshold_sample_th_arr;
width_sweep_thresholds[4] = width_1400_threshold_sample_th_arr;
width_sweep_thresholds[5] = width_1500_threshold_sample_th_arr;
width_sweep_thresholds[6] = width_1600_threshold_sample_th_arr;
width_sweep_thresholds[7] = width_1700_threshold_sample_th_arr;
width_sweep_thresholds[8] = width_1800_threshold_sample_th_arr;
width_sweep_thresholds[9] = width_1900_threshold_sample_th_arr;
width_sweep_thresholds[10] = width_2000_threshold_sample_th_arr;
width_sweep_thresholds[11] = width_2100_threshold_sample_th_arr;
width_sweep_thresholds[12] = width_2200_threshold_sample_th_arr;
width_sweep_thresholds[13] = width_2300_threshold_sample_th_arr;
width_sweep_thresholds[14] = width_2400_threshold_sample_th_arr;
width_sweep_thresholds[15] = width_2500_threshold_sample_th_arr;
width_sweep_thresholds[16] = width_2600_threshold_sample_th_arr;
width_sweep_thresholds[17] = width_2700_threshold_sample_th_arr;
width_sweep_thresholds[18] = width_2800_threshold_sample_th_arr;
width_sweep_thresholds[19] = width_2900_threshold_sample_th_arr;
width_sweep_thresholds[20] = width_3000_threshold_sample_th_arr;
width_sweep_thresholds[21] = width_3100_threshold_sample_th_arr;
width_sweep_thresholds[22] = width_3200_threshold_sample_th_arr;
width_sweep_thresholds[23] = width_3300_threshold_sample_th_arr;
width_sweep_thresholds[24] = width_3400_threshold_sample_th_arr;
width_sweep_thresholds[25] = width_3500_threshold_sample_th_arr;
width_sweep_thresholds[26] = width_3600_threshold_sample_th_arr;
width_sweep_thresholds[27] = width_3700_threshold_sample_th_arr;
width_sweep_thresholds[28] = width_3800_threshold_sample_th_arr;
width_sweep_thresholds[29] = width_3900_threshold_sample_th_arr;
width_sweep_thresholds[30] = width_4000_threshold_sample_th_arr;
width_sweep_thresholds[31] = width_4100_threshold_sample_th_arr;
width_sweep_thresholds[32] = width_4200_threshold_sample_th_arr;
width_sweep_thresholds[33] = width_4300_threshold_sample_th_arr;
width_sweep_thresholds[34] = width_4400_threshold_sample_th_arr;
width_sweep_thresholds[35] = width_4500_threshold_sample_th_arr;
width_sweep_thresholds[36] = width_4600_threshold_sample_th_arr;
width_sweep_thresholds[37] = width_4700_threshold_sample_th_arr;
width_sweep_thresholds[38] = width_4800_threshold_sample_th_arr;
width_sweep_thresholds[39] = width_4900_threshold_sample_th_arr;
width_sweep_thresholds[40] = width_5000_threshold_sample_th_arr;
end
`endif