//////////////////////////////////////////////////////////////////////////////////
// Company: AGH
// Engineer: Marcin Maj
// 
// Create Date: 07.07.2024 19:09:20
// Design Name: 
// Module Name: test_vectors.h
// Description: File contains test vectors stored in logic arrays. File is auto-generated by create_tv_file.py
// 
//////////////////////////////////////////////////////////////////////////////////

`ifndef TEST_VECTORS
`define TEST_VECTORS

localparam AMP_SWEEP_LEN   = 21;
localparam WIDTH_SWEEP_LEN = 41;
localparam RESULT_WIDTH    = 16;

typedef logic [IN_WIDTH-1:0]     wave_t [0:PULSE_SAMPLES-1];
typedef logic                    threshold_t [0:PULSE_SAMPLES-1];
typedef logic [RESULT_WIDTH-1:0] result_t;

wave_t      amplitude_sweep_waves      [0:AMP_SWEEP_LEN-1];
threshold_t amplitude_sweep_thresholds [0:AMP_SWEEP_LEN-1];
wave_t      width_sweep_waves          [0:WIDTH_SWEEP_LEN-1];
threshold_t width_sweep_thresholds     [0:WIDTH_SWEEP_LEN-1];
result_t    amplitude_sweep_results    [0:AMP_SWEEP_LEN-1];

//////////////////////////////////////////////////
// AMPLITUDE SWEEP VECTORS
//////////////////////////////////////////////////
logic [IN_WIDTH-1:0] amplitude_1_0008_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_2_0208_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_3_0408_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_4_0608_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_5_0808_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_6_1008_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_7_1208_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_8_1408_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_9_1608_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_10_1808_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_11_2008_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_12_2208_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_13_2408_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_14_2608_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_15_2808_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_16_3008_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_17_3208_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_18_3408_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_19_3608_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_20_3808_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] amplitude_21_4008_wave_arr [0:PULSE_SAMPLES-1];
logic amplitude_1_0008_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_2_0208_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_3_0408_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_4_0608_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_5_0808_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_6_1008_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_7_1208_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_8_1408_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_9_1608_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_10_1808_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_11_2008_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_12_2208_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_13_2408_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_14_2608_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_15_2808_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_16_3008_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_17_3208_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_18_3408_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_19_3608_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_20_3808_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic amplitude_21_4008_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic [RESULT_WIDTH-1:0] amplitude_1_0008_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_2_0208_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_3_0408_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_4_0608_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_5_0808_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_6_1008_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_7_1208_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_8_1408_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_9_1608_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_10_1808_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_11_2008_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_12_2208_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_13_2408_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_14_2608_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_15_2808_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_16_3008_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_17_3208_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_18_3408_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_19_3608_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_20_3808_result_result_arr [0:1];
logic [RESULT_WIDTH-1:0] amplitude_21_4008_result_result_arr [0:1];
//////////////////////////////////////////////////
// WIDTH SWEEP VECTORS
//////////////////////////////////////////////////
logic [IN_WIDTH-1:0] width_1_1000_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_2_1100_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_3_1200_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_4_1300_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_5_1400_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_6_1500_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_7_1600_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_8_1700_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_9_1800_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_10_1900_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_11_2000_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_12_2100_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_13_2200_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_14_2300_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_15_2400_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_16_2500_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_17_2600_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_18_2700_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_19_2800_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_20_2900_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_21_3000_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_22_3100_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_23_3200_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_24_3300_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_25_3400_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_26_3500_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_27_3600_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_28_3700_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_29_3800_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_30_3900_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_31_4000_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_32_4100_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_33_4200_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_34_4300_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_35_4400_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_36_4500_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_37_4600_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_38_4700_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_39_4800_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_40_4900_wave_arr [0:PULSE_SAMPLES-1];
logic [IN_WIDTH-1:0] width_41_5000_wave_arr [0:PULSE_SAMPLES-1];
logic width_1_1000_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_2_1100_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_3_1200_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_4_1300_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_5_1400_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_6_1500_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_7_1600_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_8_1700_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_9_1800_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_10_1900_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_11_2000_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_12_2100_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_13_2200_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_14_2300_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_15_2400_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_16_2500_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_17_2600_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_18_2700_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_19_2800_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_20_2900_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_21_3000_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_22_3100_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_23_3200_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_24_3300_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_25_3400_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_26_3500_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_27_3600_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_28_3700_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_29_3800_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_30_3900_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_31_4000_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_32_4100_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_33_4200_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_34_4300_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_35_4400_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_36_4500_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_37_4600_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_38_4700_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_39_4800_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_40_4900_threshold_sample_th_arr [0:PULSE_SAMPLES-1];
logic width_41_5000_threshold_sample_th_arr [0:PULSE_SAMPLES-1];

typedef enum {
  amplitude_1_0008_,
  amplitude_2_0208_,
  amplitude_3_0408_,
  amplitude_4_0608_,
  amplitude_5_0808_,
  amplitude_6_1008_,
  amplitude_7_1208_,
  amplitude_8_1408_,
  amplitude_9_1608_,
  amplitude_10_1808_,
  amplitude_11_2008_,
  amplitude_12_2208_,
  amplitude_13_2408_,
  amplitude_14_2608_,
  amplitude_15_2808_,
  amplitude_16_3008_,
  amplitude_17_3208_,
  amplitude_18_3408_,
  amplitude_19_3608_,
  amplitude_20_3808_,
  amplitude_21_4008_
} amp_testname_t;


typedef enum {
  width_1_1000_,
  width_2_1100_,
  width_3_1200_,
  width_4_1300_,
  width_5_1400_,
  width_6_1500_,
  width_7_1600_,
  width_8_1700_,
  width_9_1800_,
  width_10_1900_,
  width_11_2000_,
  width_12_2100_,
  width_13_2200_,
  width_14_2300_,
  width_15_2400_,
  width_16_2500_,
  width_17_2600_,
  width_18_2700_,
  width_19_2800_,
  width_20_2900_,
  width_21_3000_,
  width_22_3100_,
  width_23_3200_,
  width_24_3300_,
  width_25_3400_,
  width_26_3500_,
  width_27_3600_,
  width_28_3700_,
  width_29_3800_,
  width_30_3900_,
  width_31_4000_,
  width_32_4100_,
  width_33_4200_,
  width_34_4300_,
  width_35_4400_,
  width_36_4500_,
  width_37_4600_,
  width_38_4700_,
  width_39_4800_,
  width_40_4900_,
  width_41_5000_
} width_testname_t;

width_testname_t width_testname = width_1_1000_;
amp_testname_t amp_testname = amplitude_1_0008_;

initial begin
//////////////////////////////////////////////////
// LOADING AMPLITUDE SWEEP VALUES TO VECTORS
//////////////////////////////////////////////////
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_1_0008_.txt", amplitude_1_0008_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_2_0208_.txt", amplitude_2_0208_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_3_0408_.txt", amplitude_3_0408_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_4_0608_.txt", amplitude_4_0608_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_5_0808_.txt", amplitude_5_0808_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_6_1008_.txt", amplitude_6_1008_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_7_1208_.txt", amplitude_7_1208_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_8_1408_.txt", amplitude_8_1408_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_9_1608_.txt", amplitude_9_1608_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_10_1808_.txt", amplitude_10_1808_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_11_2008_.txt", amplitude_11_2008_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_12_2208_.txt", amplitude_12_2208_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_13_2408_.txt", amplitude_13_2408_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_14_2608_.txt", amplitude_14_2608_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_15_2808_.txt", amplitude_15_2808_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_16_3008_.txt", amplitude_16_3008_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_17_3208_.txt", amplitude_17_3208_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_18_3408_.txt", amplitude_18_3408_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_19_3608_.txt", amplitude_19_3608_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_20_3808_.txt", amplitude_20_3808_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_21_4008_.txt", amplitude_21_4008_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_1_0008_threshold_sample_.txt", amplitude_1_0008_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_2_0208_threshold_sample_.txt", amplitude_2_0208_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_3_0408_threshold_sample_.txt", amplitude_3_0408_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_4_0608_threshold_sample_.txt", amplitude_4_0608_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_5_0808_threshold_sample_.txt", amplitude_5_0808_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_6_1008_threshold_sample_.txt", amplitude_6_1008_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_7_1208_threshold_sample_.txt", amplitude_7_1208_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_8_1408_threshold_sample_.txt", amplitude_8_1408_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_9_1608_threshold_sample_.txt", amplitude_9_1608_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_10_1808_threshold_sample_.txt", amplitude_10_1808_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_11_2008_threshold_sample_.txt", amplitude_11_2008_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_12_2208_threshold_sample_.txt", amplitude_12_2208_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_13_2408_threshold_sample_.txt", amplitude_13_2408_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_14_2608_threshold_sample_.txt", amplitude_14_2608_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_15_2808_threshold_sample_.txt", amplitude_15_2808_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_16_3008_threshold_sample_.txt", amplitude_16_3008_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_17_3208_threshold_sample_.txt", amplitude_17_3208_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_18_3408_threshold_sample_.txt", amplitude_18_3408_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_19_3608_threshold_sample_.txt", amplitude_19_3608_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_20_3808_threshold_sample_.txt", amplitude_20_3808_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_21_4008_threshold_sample_.txt", amplitude_21_4008_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_1_0008_result_.txt", amplitude_1_0008_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_2_0208_result_.txt", amplitude_2_0208_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_3_0408_result_.txt", amplitude_3_0408_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_4_0608_result_.txt", amplitude_4_0608_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_5_0808_result_.txt", amplitude_5_0808_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_6_1008_result_.txt", amplitude_6_1008_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_7_1208_result_.txt", amplitude_7_1208_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_8_1408_result_.txt", amplitude_8_1408_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_9_1608_result_.txt", amplitude_9_1608_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_10_1808_result_.txt", amplitude_10_1808_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_11_2008_result_.txt", amplitude_11_2008_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_12_2208_result_.txt", amplitude_12_2208_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_13_2408_result_.txt", amplitude_13_2408_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_14_2608_result_.txt", amplitude_14_2608_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_15_2808_result_.txt", amplitude_15_2808_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_16_3008_result_.txt", amplitude_16_3008_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_17_3208_result_.txt", amplitude_17_3208_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_18_3408_result_.txt", amplitude_18_3408_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_19_3608_result_.txt", amplitude_19_3608_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_20_3808_result_.txt", amplitude_20_3808_result_result_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/amplitude_21_4008_result_.txt", amplitude_21_4008_result_result_arr);
//////////////////////////////////////////////////
// LOADING WIDTH SWEEP VALUES TO VECTORS
//////////////////////////////////////////////////
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1_1000_.txt", width_1_1000_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2_1100_.txt", width_2_1100_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3_1200_.txt", width_3_1200_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4_1300_.txt", width_4_1300_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_5_1400_.txt", width_5_1400_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_6_1500_.txt", width_6_1500_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_7_1600_.txt", width_7_1600_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_8_1700_.txt", width_8_1700_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_9_1800_.txt", width_9_1800_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_10_1900_.txt", width_10_1900_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_11_2000_.txt", width_11_2000_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_12_2100_.txt", width_12_2100_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_13_2200_.txt", width_13_2200_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_14_2300_.txt", width_14_2300_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_15_2400_.txt", width_15_2400_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_16_2500_.txt", width_16_2500_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_17_2600_.txt", width_17_2600_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_18_2700_.txt", width_18_2700_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_19_2800_.txt", width_19_2800_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_20_2900_.txt", width_20_2900_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_21_3000_.txt", width_21_3000_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_22_3100_.txt", width_22_3100_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_23_3200_.txt", width_23_3200_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_24_3300_.txt", width_24_3300_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_25_3400_.txt", width_25_3400_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_26_3500_.txt", width_26_3500_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_27_3600_.txt", width_27_3600_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_28_3700_.txt", width_28_3700_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_29_3800_.txt", width_29_3800_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_30_3900_.txt", width_30_3900_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_31_4000_.txt", width_31_4000_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_32_4100_.txt", width_32_4100_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_33_4200_.txt", width_33_4200_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_34_4300_.txt", width_34_4300_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_35_4400_.txt", width_35_4400_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_36_4500_.txt", width_36_4500_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_37_4600_.txt", width_37_4600_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_38_4700_.txt", width_38_4700_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_39_4800_.txt", width_39_4800_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_40_4900_.txt", width_40_4900_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_41_5000_.txt", width_41_5000_wave_arr );
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_1_1000_threshold_sample_.txt", width_1_1000_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_2_1100_threshold_sample_.txt", width_2_1100_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_3_1200_threshold_sample_.txt", width_3_1200_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_4_1300_threshold_sample_.txt", width_4_1300_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_5_1400_threshold_sample_.txt", width_5_1400_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_6_1500_threshold_sample_.txt", width_6_1500_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_7_1600_threshold_sample_.txt", width_7_1600_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_8_1700_threshold_sample_.txt", width_8_1700_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_9_1800_threshold_sample_.txt", width_9_1800_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_10_1900_threshold_sample_.txt", width_10_1900_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_11_2000_threshold_sample_.txt", width_11_2000_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_12_2100_threshold_sample_.txt", width_12_2100_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_13_2200_threshold_sample_.txt", width_13_2200_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_14_2300_threshold_sample_.txt", width_14_2300_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_15_2400_threshold_sample_.txt", width_15_2400_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_16_2500_threshold_sample_.txt", width_16_2500_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_17_2600_threshold_sample_.txt", width_17_2600_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_18_2700_threshold_sample_.txt", width_18_2700_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_19_2800_threshold_sample_.txt", width_19_2800_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_20_2900_threshold_sample_.txt", width_20_2900_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_21_3000_threshold_sample_.txt", width_21_3000_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_22_3100_threshold_sample_.txt", width_22_3100_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_23_3200_threshold_sample_.txt", width_23_3200_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_24_3300_threshold_sample_.txt", width_24_3300_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_25_3400_threshold_sample_.txt", width_25_3400_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_26_3500_threshold_sample_.txt", width_26_3500_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_27_3600_threshold_sample_.txt", width_27_3600_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_28_3700_threshold_sample_.txt", width_28_3700_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_29_3800_threshold_sample_.txt", width_29_3800_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_30_3900_threshold_sample_.txt", width_30_3900_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_31_4000_threshold_sample_.txt", width_31_4000_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_32_4100_threshold_sample_.txt", width_32_4100_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_33_4200_threshold_sample_.txt", width_33_4200_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_34_4300_threshold_sample_.txt", width_34_4300_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_35_4400_threshold_sample_.txt", width_35_4400_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_36_4500_threshold_sample_.txt", width_36_4500_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_37_4600_threshold_sample_.txt", width_37_4600_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_38_4700_threshold_sample_.txt", width_38_4700_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_39_4800_threshold_sample_.txt", width_39_4800_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_40_4900_threshold_sample_.txt", width_40_4900_threshold_sample_th_arr);
  $readmemh("D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/width_41_5000_threshold_sample_.txt", width_41_5000_threshold_sample_th_arr);
end

initial begin
amplitude_sweep_waves[0] = amplitude_1_0008_wave_arr;
amplitude_sweep_waves[1] = amplitude_2_0208_wave_arr;
amplitude_sweep_waves[2] = amplitude_3_0408_wave_arr;
amplitude_sweep_waves[3] = amplitude_4_0608_wave_arr;
amplitude_sweep_waves[4] = amplitude_5_0808_wave_arr;
amplitude_sweep_waves[5] = amplitude_6_1008_wave_arr;
amplitude_sweep_waves[6] = amplitude_7_1208_wave_arr;
amplitude_sweep_waves[7] = amplitude_8_1408_wave_arr;
amplitude_sweep_waves[8] = amplitude_9_1608_wave_arr;
amplitude_sweep_waves[9] = amplitude_10_1808_wave_arr;
amplitude_sweep_waves[10] = amplitude_11_2008_wave_arr;
amplitude_sweep_waves[11] = amplitude_12_2208_wave_arr;
amplitude_sweep_waves[12] = amplitude_13_2408_wave_arr;
amplitude_sweep_waves[13] = amplitude_14_2608_wave_arr;
amplitude_sweep_waves[14] = amplitude_15_2808_wave_arr;
amplitude_sweep_waves[15] = amplitude_16_3008_wave_arr;
amplitude_sweep_waves[16] = amplitude_17_3208_wave_arr;
amplitude_sweep_waves[17] = amplitude_18_3408_wave_arr;
amplitude_sweep_waves[18] = amplitude_19_3608_wave_arr;
amplitude_sweep_waves[19] = amplitude_20_3808_wave_arr;
amplitude_sweep_waves[20] = amplitude_21_4008_wave_arr;
amplitude_sweep_thresholds[0] = amplitude_1_0008_threshold_sample_th_arr;
amplitude_sweep_thresholds[1] = amplitude_2_0208_threshold_sample_th_arr;
amplitude_sweep_thresholds[2] = amplitude_3_0408_threshold_sample_th_arr;
amplitude_sweep_thresholds[3] = amplitude_4_0608_threshold_sample_th_arr;
amplitude_sweep_thresholds[4] = amplitude_5_0808_threshold_sample_th_arr;
amplitude_sweep_thresholds[5] = amplitude_6_1008_threshold_sample_th_arr;
amplitude_sweep_thresholds[6] = amplitude_7_1208_threshold_sample_th_arr;
amplitude_sweep_thresholds[7] = amplitude_8_1408_threshold_sample_th_arr;
amplitude_sweep_thresholds[8] = amplitude_9_1608_threshold_sample_th_arr;
amplitude_sweep_thresholds[9] = amplitude_10_1808_threshold_sample_th_arr;
amplitude_sweep_thresholds[10] = amplitude_11_2008_threshold_sample_th_arr;
amplitude_sweep_thresholds[11] = amplitude_12_2208_threshold_sample_th_arr;
amplitude_sweep_thresholds[12] = amplitude_13_2408_threshold_sample_th_arr;
amplitude_sweep_thresholds[13] = amplitude_14_2608_threshold_sample_th_arr;
amplitude_sweep_thresholds[14] = amplitude_15_2808_threshold_sample_th_arr;
amplitude_sweep_thresholds[15] = amplitude_16_3008_threshold_sample_th_arr;
amplitude_sweep_thresholds[16] = amplitude_17_3208_threshold_sample_th_arr;
amplitude_sweep_thresholds[17] = amplitude_18_3408_threshold_sample_th_arr;
amplitude_sweep_thresholds[18] = amplitude_19_3608_threshold_sample_th_arr;
amplitude_sweep_thresholds[19] = amplitude_20_3808_threshold_sample_th_arr;
amplitude_sweep_thresholds[20] = amplitude_21_4008_threshold_sample_th_arr;
amplitude_sweep_results[0] = amplitude_1_0008_result_result_arr[0];
amplitude_sweep_results[1] = amplitude_2_0208_result_result_arr[0];
amplitude_sweep_results[2] = amplitude_3_0408_result_result_arr[0];
amplitude_sweep_results[3] = amplitude_4_0608_result_result_arr[0];
amplitude_sweep_results[4] = amplitude_5_0808_result_result_arr[0];
amplitude_sweep_results[5] = amplitude_6_1008_result_result_arr[0];
amplitude_sweep_results[6] = amplitude_7_1208_result_result_arr[0];
amplitude_sweep_results[7] = amplitude_8_1408_result_result_arr[0];
amplitude_sweep_results[8] = amplitude_9_1608_result_result_arr[0];
amplitude_sweep_results[9] = amplitude_10_1808_result_result_arr[0];
amplitude_sweep_results[10] = amplitude_11_2008_result_result_arr[0];
amplitude_sweep_results[11] = amplitude_12_2208_result_result_arr[0];
amplitude_sweep_results[12] = amplitude_13_2408_result_result_arr[0];
amplitude_sweep_results[13] = amplitude_14_2608_result_result_arr[0];
amplitude_sweep_results[14] = amplitude_15_2808_result_result_arr[0];
amplitude_sweep_results[15] = amplitude_16_3008_result_result_arr[0];
amplitude_sweep_results[16] = amplitude_17_3208_result_result_arr[0];
amplitude_sweep_results[17] = amplitude_18_3408_result_result_arr[0];
amplitude_sweep_results[18] = amplitude_19_3608_result_result_arr[0];
amplitude_sweep_results[19] = amplitude_20_3808_result_result_arr[0];
amplitude_sweep_results[20] = amplitude_21_4008_result_result_arr[0];
width_sweep_waves[0] = width_1_1000_wave_arr;
width_sweep_waves[1] = width_2_1100_wave_arr;
width_sweep_waves[2] = width_3_1200_wave_arr;
width_sweep_waves[3] = width_4_1300_wave_arr;
width_sweep_waves[4] = width_5_1400_wave_arr;
width_sweep_waves[5] = width_6_1500_wave_arr;
width_sweep_waves[6] = width_7_1600_wave_arr;
width_sweep_waves[7] = width_8_1700_wave_arr;
width_sweep_waves[8] = width_9_1800_wave_arr;
width_sweep_waves[9] = width_10_1900_wave_arr;
width_sweep_waves[10] = width_11_2000_wave_arr;
width_sweep_waves[11] = width_12_2100_wave_arr;
width_sweep_waves[12] = width_13_2200_wave_arr;
width_sweep_waves[13] = width_14_2300_wave_arr;
width_sweep_waves[14] = width_15_2400_wave_arr;
width_sweep_waves[15] = width_16_2500_wave_arr;
width_sweep_waves[16] = width_17_2600_wave_arr;
width_sweep_waves[17] = width_18_2700_wave_arr;
width_sweep_waves[18] = width_19_2800_wave_arr;
width_sweep_waves[19] = width_20_2900_wave_arr;
width_sweep_waves[20] = width_21_3000_wave_arr;
width_sweep_waves[21] = width_22_3100_wave_arr;
width_sweep_waves[22] = width_23_3200_wave_arr;
width_sweep_waves[23] = width_24_3300_wave_arr;
width_sweep_waves[24] = width_25_3400_wave_arr;
width_sweep_waves[25] = width_26_3500_wave_arr;
width_sweep_waves[26] = width_27_3600_wave_arr;
width_sweep_waves[27] = width_28_3700_wave_arr;
width_sweep_waves[28] = width_29_3800_wave_arr;
width_sweep_waves[29] = width_30_3900_wave_arr;
width_sweep_waves[30] = width_31_4000_wave_arr;
width_sweep_waves[31] = width_32_4100_wave_arr;
width_sweep_waves[32] = width_33_4200_wave_arr;
width_sweep_waves[33] = width_34_4300_wave_arr;
width_sweep_waves[34] = width_35_4400_wave_arr;
width_sweep_waves[35] = width_36_4500_wave_arr;
width_sweep_waves[36] = width_37_4600_wave_arr;
width_sweep_waves[37] = width_38_4700_wave_arr;
width_sweep_waves[38] = width_39_4800_wave_arr;
width_sweep_waves[39] = width_40_4900_wave_arr;
width_sweep_waves[40] = width_41_5000_wave_arr;
width_sweep_thresholds[0] = width_1_1000_threshold_sample_th_arr;
width_sweep_thresholds[1] = width_2_1100_threshold_sample_th_arr;
width_sweep_thresholds[2] = width_3_1200_threshold_sample_th_arr;
width_sweep_thresholds[3] = width_4_1300_threshold_sample_th_arr;
width_sweep_thresholds[4] = width_5_1400_threshold_sample_th_arr;
width_sweep_thresholds[5] = width_6_1500_threshold_sample_th_arr;
width_sweep_thresholds[6] = width_7_1600_threshold_sample_th_arr;
width_sweep_thresholds[7] = width_8_1700_threshold_sample_th_arr;
width_sweep_thresholds[8] = width_9_1800_threshold_sample_th_arr;
width_sweep_thresholds[9] = width_10_1900_threshold_sample_th_arr;
width_sweep_thresholds[10] = width_11_2000_threshold_sample_th_arr;
width_sweep_thresholds[11] = width_12_2100_threshold_sample_th_arr;
width_sweep_thresholds[12] = width_13_2200_threshold_sample_th_arr;
width_sweep_thresholds[13] = width_14_2300_threshold_sample_th_arr;
width_sweep_thresholds[14] = width_15_2400_threshold_sample_th_arr;
width_sweep_thresholds[15] = width_16_2500_threshold_sample_th_arr;
width_sweep_thresholds[16] = width_17_2600_threshold_sample_th_arr;
width_sweep_thresholds[17] = width_18_2700_threshold_sample_th_arr;
width_sweep_thresholds[18] = width_19_2800_threshold_sample_th_arr;
width_sweep_thresholds[19] = width_20_2900_threshold_sample_th_arr;
width_sweep_thresholds[20] = width_21_3000_threshold_sample_th_arr;
width_sweep_thresholds[21] = width_22_3100_threshold_sample_th_arr;
width_sweep_thresholds[22] = width_23_3200_threshold_sample_th_arr;
width_sweep_thresholds[23] = width_24_3300_threshold_sample_th_arr;
width_sweep_thresholds[24] = width_25_3400_threshold_sample_th_arr;
width_sweep_thresholds[25] = width_26_3500_threshold_sample_th_arr;
width_sweep_thresholds[26] = width_27_3600_threshold_sample_th_arr;
width_sweep_thresholds[27] = width_28_3700_threshold_sample_th_arr;
width_sweep_thresholds[28] = width_29_3800_threshold_sample_th_arr;
width_sweep_thresholds[29] = width_30_3900_threshold_sample_th_arr;
width_sweep_thresholds[30] = width_31_4000_threshold_sample_th_arr;
width_sweep_thresholds[31] = width_32_4100_threshold_sample_th_arr;
width_sweep_thresholds[32] = width_33_4200_threshold_sample_th_arr;
width_sweep_thresholds[33] = width_34_4300_threshold_sample_th_arr;
width_sweep_thresholds[34] = width_35_4400_threshold_sample_th_arr;
width_sweep_thresholds[35] = width_36_4500_threshold_sample_th_arr;
width_sweep_thresholds[36] = width_37_4600_threshold_sample_th_arr;
width_sweep_thresholds[37] = width_38_4700_threshold_sample_th_arr;
width_sweep_thresholds[38] = width_39_4800_threshold_sample_th_arr;
width_sweep_thresholds[39] = width_40_4900_threshold_sample_th_arr;
width_sweep_thresholds[40] = width_41_5000_threshold_sample_th_arr;
end
`endif