
import os

TV_DIR = "./PROCESSED_TV/"
DEST_FILE_PATH = "../../CFD_rtl/CFD/CFD.srcs/sim_1/new/"
DEST_FILENAME = "test_vectors.vh"
ABSOLUTE_PATH = "D:/Studia_EiT/Magisterskie/Praca_Magisterska/DCFD/python_scripts/TV/PROCESSED_TV/"


#######################################################################################
#   READ ALL TESTVECTORS FILENAMES
#######################################################################################
file_list_unsorted = os.listdir(TV_DIR)
file_list = sorted(file_list_unsorted, key=lambda x: int(x.split('_')[1]))

wave_amp_files   = []
th_amp_files     = []
result_amp_files = []
wave_width_files = []
th_width_files   = []

# amplitude_61_.txt
for file in file_list:
    if "amplitude" in file:
        if "threshold" in file:
            th_amp_files.append(file[0:-4])
        elif "result" in file:
            result_amp_files.append(file[0:-4])
        else:
            wave_amp_files.append(file[0:-4])
    if "width" in file:
        if "threshold" in file:
            th_width_files.append(file[0:-4])
        else:
            wave_width_files.append(file[0:-4])

if (len(th_amp_files) != len(wave_amp_files)):
    print("[ERROR] number of saved amplitude files is different than threshold files")
    exit()
else:
    amp_sweep_len = len(wave_amp_files) #text files have 1 blank line

if (len(th_width_files) != len(wave_width_files)):
    print("[ERROR] number of saved amplitude files is different than threshold files")
    exit()
else:
    width_sweep_len = len(wave_width_files) #text files have 1 blank line

FILE_START = """//////////////////////////////////////////////////////////////////////////////////
// Company: AGH
// Engineer: Marcin Maj
// 
// Create Date: 07.07.2024 19:09:20
// Design Name: 
// Module Name: test_vectors.h
// Description: File contains test vectors stored in logic arrays. File is auto-generated by create_tv_file.py
// 
//////////////////////////////////////////////////////////////////////////////////

`ifndef TEST_VECTORS
`define TEST_VECTORS\n
"""
FILE_END = """`endif"""
AMP_FILES_COMMENT1 = """//////////////////////////////////////////////////
// AMPLITUDE SWEEP VECTORS
//////////////////////////////////////////////////
"""
AMP_FILES_COMMENT_RESULTS = """//////////////////////////////////////////////////
// AMPLITUDE SWEEP RESULTS
//////////////////////////////////////////////////
"""
TH_FILES_COMMENT1 = """//////////////////////////////////////////////////
// WIDTH SWEEP VECTORS
//////////////////////////////////////////////////
"""
AMP_FILES_COMMENT2 =  """//////////////////////////////////////////////////
// LOADING AMPLITUDE SWEEP VALUES TO VECTORS
//////////////////////////////////////////////////
"""
TH_FILES_COMMENT2 =  """//////////////////////////////////////////////////
// LOADING WIDTH SWEEP VALUES TO VECTORS
//////////////////////////////////////////////////
"""
INITIAL_START = """initial begin\n"""
INITIAL_END   = """end\n"""

PARAMS = f"""localparam AMP_SWEEP_LEN   = {amp_sweep_len};
localparam WIDTH_SWEEP_LEN = {width_sweep_len};
localparam RESULT_WIDTH    = 16;\n
"""
print("[INFO] Check if RESULT_WIDTH is set properly (it's hardcoded, line 89)")

WAVE_TYPEDEF                = "typedef logic [IN_WIDTH-1:0]     wave_t [0:PULSE_SAMPLES-1];\n"
THRESHOLD_TYPEDEF           = "typedef logic                    threshold_t [0:PULSE_SAMPLES-1];\n"
RESULTS_TYPEDEF             = "typedef logic [RESULT_WIDTH-1:0] result_t;\n"

WIDH_SWEEP_WAVE_ARR         = f'wave_t      amplitude_sweep_waves      [0:AMP_SWEEP_LEN-1];\n'
WIDH_SWEEP_TH_ARR           = f'threshold_t amplitude_sweep_thresholds [0:AMP_SWEEP_LEN-1];\n'
AMPLITUDE_SWEEP_RESULTS_ARR = f'result_t    amplitude_sweep_results    [0:AMP_SWEEP_LEN-1];\n'

AMPLITUDE_SWEEP_WAVE_ARR    = f'wave_t      width_sweep_waves          [0:WIDTH_SWEEP_LEN-1];\n'
AMPLITUDE_SWEEP_TH_ARR      = f'threshold_t width_sweep_thresholds     [0:WIDTH_SWEEP_LEN-1];\n'

amplitude_waves_names = []
width_waves_names     = []

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# CREATE TYPEDEFS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tv_file = open(DEST_FILE_PATH+DEST_FILENAME, "w")
tv_file.write(FILE_START)
tv_file.write(PARAMS)
tv_file.write(WAVE_TYPEDEF)
tv_file.write(THRESHOLD_TYPEDEF)
tv_file.write(RESULTS_TYPEDEF)
tv_file.write("\n")
tv_file.write(WIDH_SWEEP_WAVE_ARR)
tv_file.write(WIDH_SWEEP_TH_ARR)
tv_file.write(AMPLITUDE_SWEEP_WAVE_ARR)
tv_file.write(AMPLITUDE_SWEEP_TH_ARR)
tv_file.write(AMPLITUDE_SWEEP_RESULTS_ARR)
tv_file.write("\n")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# CREATE ARRAYS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# crate named arrays to store values from each file
# next step is to assign those 2D arrays to one 3D array
tv_file.write(AMP_FILES_COMMENT1)
for filename in wave_amp_files:
    tv_file.write(f'logic [IN_WIDTH-1:0] {filename}wave_arr [0:PULSE_SAMPLES-1];\n')
for filename in th_amp_files:
    tv_file.write(f'logic {filename}th_arr [0:PULSE_SAMPLES-1];\n')
for filename in result_amp_files:
    tv_file.write(f'logic [RESULT_WIDTH-1:0] {filename}result_arr [0:1];\n')
tv_file.write(TH_FILES_COMMENT1)
for filename in wave_width_files:
    tv_file.write(f'logic [IN_WIDTH-1:0] {filename}wave_arr [0:PULSE_SAMPLES-1];\n')
for filename in th_width_files:
    tv_file.write(f'logic {filename}th_arr [0:PULSE_SAMPLES-1];\n')


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# CREATE ENUMS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tv_file.write("\ntypedef enum {\n")
for i, filename in enumerate(wave_amp_files):
    if i<amp_sweep_len-1:
        tv_file.write(f'  {filename},\n')
    else:
        tv_file.write(f'  {filename}\n')
tv_file.write("} amp_testname_t;\n\n")

tv_file.write("\ntypedef enum {\n")
for i, filename in enumerate(wave_width_files):
    if i<width_sweep_len-1:
        tv_file.write(f'  {filename},\n')
    else:
        tv_file.write(f'  {filename}\n')
tv_file.write("} width_testname_t;\n\n")
tv_file.write(f'width_testname_t width_testname = {wave_width_files[0]};\n')
tv_file.write(f'amp_testname_t amp_testname = {wave_amp_files[0]};\n\n')


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# LOAD DATA FROM FILES TO ARRAYS - $readmemh
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tv_file.write(INITIAL_START)
tv_file.write(AMP_FILES_COMMENT2)
# read each file using $readmemh and store it in named array
for filename in wave_amp_files:
    tv_file.write(f'  $readmemh("{ABSOLUTE_PATH}{filename}.txt", {filename}wave_arr );\n')
for filename in th_amp_files:
    tv_file.write(f'  $readmemh("{ABSOLUTE_PATH}{filename}.txt", {filename}th_arr);\n')
for filename in result_amp_files:
    tv_file.write(f'  $readmemh("{ABSOLUTE_PATH}{filename}.txt", {filename}result_arr);\n')
tv_file.write(TH_FILES_COMMENT2)
for filename in wave_width_files:
    tv_file.write(f'  $readmemh("{ABSOLUTE_PATH}{filename}.txt", {filename}wave_arr );\n')
for filename in th_width_files:
    tv_file.write(f'  $readmemh("{ABSOLUTE_PATH}{filename}.txt", {filename}th_arr);\n')
tv_file.write(INITIAL_END)

tv_file.write("\n")
tv_file.write(INITIAL_START)
# store each named array in one bigger array
i = 0
for filename in wave_amp_files:
    tv_file.write(f'amplitude_sweep_waves[{i}] = {filename}wave_arr;\n')
    i = i + 1

i = 0
for filename in th_amp_files:
    tv_file.write(f'amplitude_sweep_thresholds[{i}] = {filename}th_arr;\n')
    i = i + 1

i = 0
for filename in result_amp_files:
    #tv_file.write(f'amplitude_sweep_results[{i}] = {{ << {{ {filename}result_arr}}}}; // cast from unpacked to packed array\n')
    tv_file.write(f'amplitude_sweep_results[{i}] = {filename}result_arr[0];\n')
    i = i + 1

i = 0
for filename in wave_width_files:
    tv_file.write(f'width_sweep_waves[{i}] = {filename}wave_arr;\n')
    i = i + 1
    
i = 0
for filename in th_width_files:
    tv_file.write(f'width_sweep_thresholds[{i}] = {filename}th_arr;\n')
    i = i + 1

tv_file.write(INITIAL_END)
# tv_file.write(INITIAL_START)
# tv_file.write(AMP_FILES_COMMENT2)
# i = 0
# for filename in wave_amp_files:
#     tv_file.write(f'  $readmemh("{ABSOLUTE_PATH}{filename}.txt", amplitude_sweep_waves[{i}]);\n')
#     i = i + 1
# i = 0
# for filename in th_amp_files:
#     tv_file.write(f'  $readmemh("{ABSOLUTE_PATH}{filename}.txt", amplitude_sweep_thresholds[{i}]);\n')
#     i = i + 1

# tv_file.write(TH_FILES_COMMENT2)
# i = 0
# for filename in wave_width_files:
#     tv_file.write(f'  $readmemh("{ABSOLUTE_PATH}{filename}.txt", width_sweep_waves[{i}]);\n')
#     i = i + 1
# i = 0
# for filename in th_width_files:
#     tv_file.write(f'  $readmemh("{ABSOLUTE_PATH}{filename}.txt", width_sweep_thresholds[{i}]);\n')
#     i = i + 1
# tv_file.write(INITIAL_END)

# tv_file.write(INITIAL_START)
# tv_file.write()
# tv_file.write(INITIAL_END)
tv_file.write(FILE_END)